export const GET_SERVER_ERRORS= "GET_SERVER_ERRORS";
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SERVER_STATUS = "SET_SERVER_STATUS";
